import { useEffect, useState } from 'react';
import Navbar from '../components/Navbar';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer, PieChart, Pie, Cell } from 'recharts';
import { Download, TrendingUp, TrendingDown, FileText } from 'lucide-react';
import axios from 'axios';
import { useAuth } from '../context/AuthContext';
import jsPDF from 'jspdf';

export default function Report() {
  const { user } = useAuth();
  const [monthlyData, setMonthlyData] = useState([]);
  const [currentStats, setCurrentStats] = useState({ claimable: 0, notClaimable: 0, review: 0, totalGST: 0, totalSpent: 0 });
  const [loading, setLoading] = useState(true);
  const [exportLoading, setExportLoading] = useState(false);

  useEffect(() => {
    const fetchData = async () => {
      try {
        const res = await axios.get('/reports/summary');
        const { monthly, current } = res.data;
        setMonthlyData(monthly || []);
        setCurrentStats(current || {});
      } catch (err) {
        console.error(err);
        // Fallback demo data
        setMonthlyData(getDemoData());
        setCurrentStats({ claimable: 4830, notClaimable: 2100, review: 900, totalGST: 7830, totalSpent: 52000 });
      } finally {
        setLoading(false);
      }
    };
    fetchData();
  }, []);

  const exportPDF = async () => {
    setExportLoading(true);
    try {
      const doc = new jsPDF();
      
      // Header
      doc.setFillColor(0, 212, 170);
      doc.rect(0, 0, 210, 40, 'F');
      doc.setTextColor(15, 17, 23);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(24);
      doc.text('ITClaim — GST ITC Report', 20, 25);

      // Sub header
      doc.setFillColor(26, 29, 39);
      doc.rect(0, 40, 210, 15, 'F');
      doc.setTextColor(139, 144, 167);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      const now = new Date();
      doc.text(`${user?.businessName || user?.name} | Generated: ${now.toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}`, 20, 50);
      if (user?.gstin) doc.text(`GSTIN: ${user.gstin}`, 130, 50);

      // Summary box
      doc.setFillColor(26, 29, 39);
      doc.rect(15, 65, 180, 55, 'F');
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(12);
      doc.setTextColor(255, 255, 255);
      doc.text('Current Month Summary', 20, 78);

      const summaryItems = [
        { label: 'Total GST Paid', value: `Rs.${currentStats.totalGST?.toLocaleString('en-IN') || 0}` },
        { label: 'ITC Claimable', value: `Rs.${currentStats.claimable?.toLocaleString('en-IN') || 0}` },
        { label: 'Not Claimable', value: `Rs.${currentStats.notClaimable?.toLocaleString('en-IN') || 0}` },
        { label: 'Needs Review', value: `Rs.${currentStats.review?.toLocaleString('en-IN') || 0}` },
      ];
      summaryItems.forEach((item, i) => {
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(10);
        doc.setTextColor(139, 144, 167);
        doc.text(item.label, 20, 90 + i * 9);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(0, 212, 170);
        doc.text(item.value, 140, 90 + i * 9);
      });

      // Monthly trend
      doc.setTextColor(255, 255, 255);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(14);
      doc.text('Monthly ITC Trend', 20, 140);

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.setTextColor(139, 144, 167);
      const headers = ['Month', 'GST Paid', 'ITC Claimable', 'Missed', 'Saved'];
      headers.forEach((h, i) => doc.text(h, 20 + i * 36, 152));

      doc.setFillColor(42, 47, 69);
      doc.rect(15, 154, 180, 0.5, 'F');

      monthlyData.forEach((row, i) => {
        const y = 162 + i * 9;
        doc.setTextColor(255, 255, 255);
        doc.text(row.month || '', 20, y);
        doc.setTextColor(139, 144, 167);
        doc.text(`Rs.${(row.totalGST || 0).toLocaleString('en-IN')}`, 56, y);
        doc.setTextColor(0, 212, 170);
        doc.text(`Rs.${(row.claimable || 0).toLocaleString('en-IN')}`, 92, y);
        doc.setTextColor(255, 77, 77);
        doc.text(`Rs.${(row.notClaimable || 0).toLocaleString('en-IN')}`, 128, y);
        doc.setTextColor(0, 212, 170);
        const pct = row.totalGST > 0 ? Math.round((row.claimable / row.totalGST) * 100) : 0;
        doc.text(`${pct}%`, 164, y);
      });

      // Footer
      doc.setFillColor(15, 17, 23);
      doc.rect(0, 270, 210, 27, 'F');
      doc.setTextColor(74, 79, 106);
      doc.setFontSize(8);
      doc.text('Generated by ITClaim (itclaim.in) · For reference only · Consult your CA before filing', 20, 282);
      doc.text('This is not a legal document. ITC claims are subject to GST rules and vendor compliance.', 20, 290);

      doc.save(`ITClaim-Report-${new Date().toISOString().slice(0, 7)}.pdf`);
    } catch (err) {
      console.error('PDF export error:', err);
    } finally {
      setExportLoading(false);
    }
  };

  const netPayable = currentStats.totalGST - currentStats.claimable;
  const savingsRate = currentStats.totalGST > 0 ? Math.round((currentStats.claimable / currentStats.totalGST) * 100) : 0;

  const pieData = [
    { name: 'Claimable', value: currentStats.claimable || 0, color: '#00D4AA' },
    { name: 'Review', value: currentStats.review || 0, color: '#F5A623' },
    { name: 'Not Claimable', value: currentStats.notClaimable || 0, color: '#FF4D4D' },
  ].filter(d => d.value > 0);

  const CustomTooltip = ({ active, payload, label }) => {
    if (!active || !payload?.length) return null;
    return (
      <div style={{ background: 'var(--bg-elevated)', border: '1px solid var(--border)', borderRadius: 8, padding: '10px 14px' }}>
        <p style={{ fontWeight: 600, marginBottom: 6, fontSize: 13 }}>{label}</p>
        {payload.map(p => (
          <p key={p.name} style={{ fontSize: 12, color: p.color }}>
            {p.name}: ₹{Number(p.value).toLocaleString('en-IN')}
          </p>
        ))}
      </div>
    );
  };

  return (
    <div style={{ display: 'flex', minHeight: '100vh' }}>
      <Navbar />
      <main className="main-content">

        {/* Header */}
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 24, flexWrap: 'wrap', gap: 12 }}>
          <div>
            <h1 style={{ fontFamily: 'Space Grotesk', fontSize: 24, fontWeight: 700, marginBottom: 4 }}>ITC Report</h1>
            <p style={{ color: 'var(--text-secondary)', fontSize: 14 }}>Monthly breakdown for your CA and tax filing</p>
          </div>
          <button id="export-pdf" onClick={exportPDF} className="btn-primary" disabled={exportLoading}>
            {exportLoading ? <span className="spinner" style={{ width: 14, height: 14 }} /> : <Download size={15} />}
            Export PDF
          </button>
        </div>

        {/* Share with CA callout */}
        <div style={{ marginBottom: 20, padding: '12px 16px', borderRadius: 8, background: 'rgba(0,212,170,0.06)', border: '1px solid rgba(0,212,170,0.2)', display: 'flex', alignItems: 'center', gap: 12 }}>
          <FileText size={16} style={{ color: 'var(--accent-green)', flexShrink: 0 }} />
          <span style={{ fontSize: 13, color: 'var(--text-secondary)' }}>
            💡 Export this report and share it with your CA. They'll use this to file your GSTR-3B and claim your ITC before the deadline.
          </span>
        </div>

        {/* Current month cards */}
        {loading ? (
          <div style={{ display: 'flex', justifyContent: 'center', padding: 60 }}>
            <span className="spinner" style={{ width: 32, height: 32 }} />
          </div>
        ) : (
          <>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(160px, 1fr))', gap: 16, marginBottom: 24 }}>
              <SummaryCard label="Total GST Paid" value={currentStats.totalGST} color="var(--text-primary)" />
              <SummaryCard label="ITC Claimable" value={currentStats.claimable} color="var(--accent-green)" highlight />
              <SummaryCard label="Not Claimable" value={currentStats.notClaimable} color="var(--accent-red)" />
              <SummaryCard label="Needs Review" value={currentStats.review} color="var(--accent-amber)" />
              <div className="card" style={{ padding: 16, gridColumn: 'auto' }}>
                <div style={{ fontSize: 11, color: 'var(--text-muted)', fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: 6 }}>Net GST Payable</div>
                <div style={{ fontFamily: 'Space Grotesk', fontSize: 22, fontWeight: 700, color: netPayable < 0 ? 'var(--accent-green)' : 'var(--text-primary)' }}>
                  ₹{Math.max(0, netPayable).toLocaleString('en-IN')}
                </div>
                <div style={{ fontSize: 11, color: netPayable > 0 ? 'var(--accent-red)' : 'var(--accent-green)', marginTop: 4, display: 'flex', alignItems: 'center', gap: 4 }}>
                  {netPayable > 0 ? <TrendingDown size={12} /> : <TrendingUp size={12} />}
                  {savingsRate}% recovery rate
                </div>
              </div>
            </div>

            {/* Charts */}
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(360px, 1fr))', gap: 20, marginBottom: 20 }}>

              {/* Bar chart */}
              <div className="card">
                <h2 style={{ fontFamily: 'Space Grotesk', fontSize: 16, fontWeight: 600, marginBottom: 20 }}>Month-by-Month ITC Trend</h2>
                {monthlyData.length > 0 ? (
                  <ResponsiveContainer width="100%" height={240}>
                    <BarChart data={monthlyData} margin={{ top: 0, right: 0, left: -20, bottom: 0 }}>
                      <CartesianGrid strokeDasharray="3 3" stroke="var(--border)" />
                      <XAxis dataKey="month" tick={{ fill: 'var(--text-muted)', fontSize: 11 }} />
                      <YAxis tick={{ fill: 'var(--text-muted)', fontSize: 11 }} tickFormatter={v => `₹${(v/1000).toFixed(0)}k`} />
                      <Tooltip content={<CustomTooltip />} />
                      <Legend wrapperStyle={{ fontSize: 12, color: 'var(--text-secondary)' }} />
                      <Bar dataKey="claimable" name="ITC Claimable" fill="#00D4AA" radius={[4, 4, 0, 0]} />
                      <Bar dataKey="notClaimable" name="Not Claimable" fill="rgba(255,77,77,0.5)" radius={[4, 4, 0, 0]} />
                      <Bar dataKey="review" name="Review" fill="rgba(245,166,35,0.5)" radius={[4, 4, 0, 0]} />
                    </BarChart>
                  </ResponsiveContainer>
                ) : (
                  <div className="empty-state" style={{ padding: 40 }}>
                    <div className="empty-state-icon">📊</div>
                    <div className="empty-state-title">No data yet</div>
                    <div className="empty-state-desc">Add expenses to see your ITC trend</div>
                  </div>
                )}
              </div>

              {/* Pie chart */}
              <div className="card">
                <h2 style={{ fontFamily: 'Space Grotesk', fontSize: 16, fontWeight: 600, marginBottom: 20 }}>Current Month Distribution</h2>
                {pieData.length > 0 ? (
                  <>
                    <ResponsiveContainer width="100%" height={200}>
                      <PieChart>
                        <Pie data={pieData} cx="50%" cy="50%" innerRadius={60} outerRadius={90}
                          paddingAngle={3} dataKey="value">
                          {pieData.map((entry, index) => (
                            <Cell key={index} fill={entry.color} />
                          ))}
                        </Pie>
                        <Tooltip content={({ active, payload }) => {
                          if (!active || !payload?.length) return null;
                          const d = payload[0].payload;
                          return (
                            <div style={{ background: 'var(--bg-elevated)', border: '1px solid var(--border)', borderRadius: 8, padding: '8px 12px', fontSize: 12 }}>
                              <span style={{ color: d.color, fontWeight: 600 }}>{d.name}: </span>
                              ₹{d.value.toLocaleString('en-IN')}
                            </div>
                          );
                        }} />
                      </PieChart>
                    </ResponsiveContainer>
                    <div style={{ display: 'flex', gap: 12, justifyContent: 'center', flexWrap: 'wrap', marginTop: 8 }}>
                      {pieData.map(d => (
                        <div key={d.name} style={{ display: 'flex', alignItems: 'center', gap: 6, fontSize: 12 }}>
                          <div style={{ width: 10, height: 10, borderRadius: 2, background: d.color }} />
                          <span style={{ color: 'var(--text-secondary)' }}>{d.name}</span>
                        </div>
                      ))}
                    </div>
                  </>
                ) : (
                  <div className="empty-state" style={{ padding: 40 }}>
                    <div className="empty-state-icon">🥧</div>
                    <div className="empty-state-title">No data yet</div>
                    <div className="empty-state-desc">Add expenses to see the distribution</div>
                  </div>
                )}
              </div>
            </div>

            {/* Monthly breakdown table */}
            {monthlyData.length > 0 && (
              <div className="card" style={{ padding: 0, overflow: 'hidden' }}>
                <div style={{ padding: '16px 20px', borderBottom: '1px solid var(--border)' }}>
                  <h2 style={{ fontFamily: 'Space Grotesk', fontSize: 16, fontWeight: 600 }}>Monthly Breakdown</h2>
                </div>
                <div style={{ overflowX: 'auto' }}>
                  <table className="data-table" style={{ minWidth: 600 }}>
                    <thead>
                      <tr>
                        <th>Month</th>
                        <th>Total GST Paid</th>
                        <th>ITC Claimable</th>
                        <th>Not Claimable</th>
                        <th>Review</th>
                        <th>Recovery Rate</th>
                      </tr>
                    </thead>
                    <tbody>
                      {monthlyData.map(row => (
                        <tr key={row.month}>
                          <td style={{ fontWeight: 500 }}>{row.month}</td>
                          <td style={{ fontFamily: 'JetBrains Mono', fontSize: 13 }}>₹{(row.totalGST || 0).toLocaleString('en-IN')}</td>
                          <td style={{ fontFamily: 'JetBrains Mono', fontSize: 13, color: 'var(--accent-green)' }}>₹{(row.claimable || 0).toLocaleString('en-IN')}</td>
                          <td style={{ fontFamily: 'JetBrains Mono', fontSize: 13, color: 'var(--accent-red)' }}>₹{(row.notClaimable || 0).toLocaleString('en-IN')}</td>
                          <td style={{ fontFamily: 'JetBrains Mono', fontSize: 13, color: 'var(--accent-amber)' }}>₹{(row.review || 0).toLocaleString('en-IN')}</td>
                          <td>
                            <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                              <div className="progress-bar" style={{ flex: 1, minWidth: 60 }}>
                                <div className="progress-fill" style={{ width: `${row.totalGST > 0 ? (row.claimable / row.totalGST) * 100 : 0}%` }} />
                              </div>
                              <span style={{ fontSize: 12, color: 'var(--accent-green)', fontWeight: 600, minWidth: 35 }}>
                                {row.totalGST > 0 ? Math.round((row.claimable / row.totalGST) * 100) : 0}%
                              </span>
                            </div>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            )}
          </>
        )}
      </main>
    </div>
  );
}

function SummaryCard({ label, value, color, highlight }) {
  return (
    <div className="card" style={{ padding: 16, ...(highlight ? { border: '1px solid rgba(0,212,170,0.3)' } : {}) }}>
      <div style={{ fontSize: 11, color: 'var(--text-muted)', fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: 6 }}>{label}</div>
      <div style={{ fontFamily: 'Space Grotesk', fontSize: 22, fontWeight: 700, color }}>₹{(value || 0).toLocaleString('en-IN')}</div>
    </div>
  );
}

function getDemoData() {
  const months = [];
  const now = new Date();
  for (let i = 5; i >= 0; i--) {
    const d = new Date(now.getFullYear(), now.getMonth() - i, 1);
    const label = d.toLocaleDateString('en-IN', { month: 'short', year: '2-digit' });
    const claimable = Math.round(2000 + Math.random() * 4000);
    const notClaimable = Math.round(500 + Math.random() * 1500);
    const review = Math.round(300 + Math.random() * 800);
    months.push({ month: label, claimable, notClaimable, review, totalGST: claimable + notClaimable + review });
  }
  return months;
}
